spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/TradeWin?serveTimeZone=Australia/sydney&useUnicode=true&characterEncoding=utf-8&&userSSL=false
    username: root
    password: 19951005
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username: twolflee@163.com
    password: NZESWWWQXSMSPEHV
    default-encoding: utf-8
    properties:
      mail:
        debug: true
mybatis:
  configuration:
    map-underscore-to-camel-case: true
